# Generated by Django 5.2.4 on 2025-07-28 12:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpBotDetection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_agent', models.TextField()),
                ('endpoint', models.CharField(max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('request_interval', models.FloatField(blank=True, null=True)),
                ('payload_schema_valid', models.BooleanField(default=True)),
                ('cookies_present', models.BooleanField(default=False)),
                ('confidence', models.FloatField()),
                ('suspicious_headers', models.JSONField(blank=True, default=list)),
                ('request_fingerprint', models.CharField(blank=True, max_length=64, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('is_headless_browser', models.BooleanField(default=False)),
                ('automation_detected', models.BooleanField(default=False)),
                ('rate_limit_exceeded', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'httpbot_detection',
                'ordering': ['-timestamp'],
            },
        ),
    ]
