# Generated by Django 5.2.4 on 2025-08-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpbot_detector', '0002_httpbotdetection_classification'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpbotdetection',
            name='usai_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
