# Generated by Django 5.2.4 on 2025-08-05 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('httpbot_detector', '0003_httpbotdetection_usai_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='httpbotdetection',
            name='usai_id',
        ),
    ]
