# Generated by Django 5.2.4 on 2025-08-05 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpbot_detector', '0004_remove_httpbotdetection_usai_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpbotdetection',
            name='headers',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
