# Generated by Django 5.2.4 on 2025-08-06 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('httpbot_detector', '0005_httpbotdetection_headers'),
    ]

    operations = [
        migrations.AddField(
            model_name='httpbotdetection',
            name='cookies',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
