# Generated by Django 5.1.7 on 2025-06-25 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usai_id', models.CharField(max_length=255, unique=True)),
                ('failed_attempts', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='UserBehavior_v2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usai_id', models.CharField(max_length=255)),
                ('cursor_movements', models.JSONField()),
                ('key_press_times', models.JSONField()),
                ('key_hold_times', models.JSONField()),
                ('click_timestamps', models.JSONField()),
                ('click_intervals', models.JSONField(default=list)),
                ('cursor_speeds', models.JSONField()),
                ('cursor_acceleration', models.JSONField()),
                ('cursor_curvature', models.JSONField()),
                ('paste_detected', models.BooleanField()),
                ('total_time', models.IntegerField()),
                ('classification', models.CharField(max_length=10)),
                ('human_score', models.FloatField()),
                ('bot_score', models.FloatField()),
                ('human_indicators', models.JSONField()),
                ('bot_indicators', models.JSONField()),
                ('bot_fingerprint_score', models.FloatField(default=0)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_feature_ratio', models.FloatField(default=0)),
                ('mouse_movement_debug', models.JSONField(default=dict)),
                ('speed_calculation_debug', models.JSONField(default=dict)),
                ('post_paste_activity', models.JSONField(default=dict)),
                ('keyboard_patterns', models.JSONField(default=list)),
                ('suspicious_patterns', models.JSONField(default=list)),
                ('action_count', models.IntegerField(default=0)),
                ('is_automated_browser', models.BooleanField(default=False)),
                ('cursor_entropy', models.FloatField(default=0)),
                ('scroll_speeds', models.JSONField(default=list)),
                ('scroll_changes', models.IntegerField(default=0)),
                ('idle_time', models.IntegerField(default=0)),
                ('honeypot_value', models.CharField(blank=True, max_length=255, null=True)),
                ('tabkeycount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_behavior_v2',
                'indexes': [models.Index(fields=['usai_id'], name='user_behavi_usai_id_e9aa27_idx'), models.Index(fields=['timestamp'], name='user_behavi_timesta_8ffa0b_idx'), models.Index(fields=['classification'], name='user_behavi_classif_284d76_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBehavior_v3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usai_id', models.CharField(max_length=255)),
                ('cursor_movements', models.JSONField()),
                ('key_press_times', models.JSONField()),
                ('key_hold_times', models.JSONField()),
                ('click_timestamps', models.JSONField()),
                ('click_intervals', models.JSONField(default=list)),
                ('cursor_speeds', models.JSONField()),
                ('cursor_acceleration', models.JSONField()),
                ('cursor_curvature', models.JSONField()),
                ('paste_detected', models.BooleanField()),
                ('total_time', models.IntegerField()),
                ('classification', models.CharField(max_length=10)),
                ('human_score', models.FloatField()),
                ('bot_score', models.FloatField()),
                ('human_indicators', models.JSONField()),
                ('bot_indicators', models.JSONField()),
                ('bot_fingerprint_score', models.FloatField(default=0)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_feature_ratio', models.FloatField(default=0)),
                ('mouse_movement_debug', models.JSONField(default=dict)),
                ('speed_calculation_debug', models.JSONField(default=dict)),
                ('post_paste_activity', models.JSONField(default=dict)),
                ('keyboard_patterns', models.JSONField(default=list)),
                ('suspicious_patterns', models.JSONField(default=list)),
                ('action_count', models.IntegerField(default=0)),
                ('is_automated_browser', models.BooleanField(default=False)),
                ('cursor_entropy', models.FloatField(default=0)),
                ('scroll_speeds', models.JSONField(default=list)),
                ('scroll_changes', models.IntegerField(default=0)),
                ('idle_time', models.IntegerField(default=0)),
                ('honeypot_value', models.CharField(blank=True, max_length=255, null=True)),
                ('tabkeycount', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'user_behavior_v3',
                'indexes': [models.Index(fields=['usai_id'], name='user_behavi_usai_id_7ececf_idx'), models.Index(fields=['timestamp'], name='user_behavi_timesta_cd64ef_idx'), models.Index(fields=['classification'], name='user_behavi_classif_9ab153_idx')],
            },
        ),
    ]
