# Generated by Django 5.1.7 on 2025-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBehavior_v1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usai_id', models.CharField(max_length=255)),
                ('cursor_movements', models.JSONField()),
                ('key_press_times', models.JSONField()),
                ('key_hold_times', models.JSONField()),
                ('click_timestamps', models.JSONField()),
                ('click_intervals', models.JSONField(default=list)),
                ('cursor_speeds', models.JSONField()),
                ('cursor_acceleration', models.JSONField()),
                ('cursor_curvature', models.JSONField()),
                ('paste_detected', models.BooleanField()),
                ('total_time', models.IntegerField()),
                ('classification', models.CharField(max_length=10)),
                ('human_score', models.FloatField()),
                ('bot_score', models.FloatField()),
                ('human_indicators', models.JSONField()),
                ('bot_indicators', models.JSONField()),
                ('bot_fingerprint_score', models.FloatField(default=0)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_feature_ratio', models.FloatField(default=0)),
                ('mouse_movement_debug', models.JSONField(default=dict)),
                ('speed_calculation_debug', models.JSONField(default=dict)),
                ('post_paste_activity', models.JSONField(default=dict)),
                ('keyboard_patterns', models.JSONField(default=list)),
                ('suspicious_patterns', models.JSONField(default=list)),
                ('action_count', models.IntegerField(default=0)),
                ('is_automated_browser', models.BooleanField(default=False)),
                ('cursor_entropy', models.FloatField(default=0)),
                ('scroll_speeds', models.JSONField(default=list)),
                ('scroll_changes', models.IntegerField(default=0)),
                ('idle_time', models.IntegerField(default=0)),
                ('honeypot_value', models.CharField(blank=True, max_length=255, null=True)),
                ('tabkeycount', models.IntegerField(default=0)),
                ('cursorAngleVariance', models.FloatField(default=0)),
            ],
            options={
                'db_table': 'UserBehavior_v1',
                'indexes': [models.Index(fields=['usai_id'], name='user_behavi_usai_id_cb1932_idx'), models.Index(fields=['timestamp'], name='user_behavi_timesta_989e69_idx'), models.Index(fields=['classification'], name='user_behavi_classif_f6c0ec_idx')],
            },
        ),
    ]
