# Generated by Django 5.1.7 on 2025-06-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0002_userbehavior_v1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbehavior_v1',
            name='cursorAngleVariance',
        ),
    ]
