# Generated by Django 5.1.7 on 2025-06-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0003_remove_userbehavior_v1_cursoranglevariance'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior_v1',
            name='cursorAngleVariance',
            field=models.FloatField(default=0),
        ),
    ]
