# Generated by Django 5.1.7 on 2025-07-01 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0005_alter_userbehavior_v1_cursoranglevariance'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userbehavior_v1',
            new_name='UserBehavio_usai_id_2bd193_idx',
            old_name='user_behavi_usai_id_cb1932_idx',
        ),
        migrations.RenameIndex(
            model_name='userbehavior_v1',
            new_name='UserBehavio_timesta_3f5c65_idx',
            old_name='user_behavi_timesta_989e69_idx',
        ),
        migrations.RenameIndex(
            model_name='userbehavior_v1',
            new_name='UserBehavio_classif_3705be_idx',
            old_name='user_behavi_classif_f6c0ec_idx',
        ),
        migrations.AddField(
            model_name='userbehavior_v1',
            name='hesitation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userbehavior_v1',
            name='micropause',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userbehavior_v1',
            name='mouseJitter',
            field=models.JSONField(default=list),
        ),
        migrations.AlterModelTable(
            name='userbehavior_v1',
            table='UserBehavior_v1',
        ),
    ]
