# Generated by Django 5.1.7 on 2025-07-02 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0006_rename_user_behavi_usai_id_cb1932_idx_userbehavio_usai_id_2bd193_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior_v2',
            name='idle_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
