# Generated by Django 5.1.7 on 2025-07-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0007_alter_userbehavior_v2_idle_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior_v1',
            name='idle_time',
            field=models.BigIntegerField(default=0),
        ),
    ]
