# Generated by Django 5.2.4 on 2025-07-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0008_alter_userbehavior_v1_idle_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbehavior_v2',
            name='canvas_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='cursorAngleVariance',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='devicefingerprint',
            field=models.CharField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='evasion_signals',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='gpu_info',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='hesitation',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='micropause',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='missing_canvas_fingerprint',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='mouseJitter',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='timing_metrics',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='userbehavior_v2',
            name='unsualscreenresolution',
            field=models.JSONField(default=dict),
        ),
    ]
