# Generated by Django 5.2.4 on 2025-07-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captchaApp', '0010_userbehavior_v3_canvas_metrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbehavior_v3',
            name='idle_time',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userbehavior_v3',
            name='total_time',
            field=models.BigIntegerField(),
        ),
    ]
