# Generated by Django 5.2.5 on 2025-08-14 18:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier', max_length=100)),
                ('user_auth', models.CharField(choices=[('Authorized_user', 'Authorized User'), ('Unauthorized_user', 'Unauthorized User')], help_text='User authorization status', max_length=20)),
                ('cursor_movements', models.JSONField(default=list, help_text='Store array of movements')),
                ('key_press_times', models.JSONField(default=list, help_text='Store array of timestamps')),
                ('key_hold_times', models.JSONField(default=list, help_text='Store array of hold durations')),
                ('click_timestamps', models.JSONField(default=list, help_text='Store array of click times')),
                ('click_intervals', models.JSONField(default=list, help_text='Store array of intervals between clicks')),
                ('cursor_speeds', models.JSONField(default=list, help_text='Store array of speeds')),
                ('cursor_acceleration', models.JSONField(default=list, help_text='Store array of accelerations')),
                ('cursor_curvature', models.JSONField(default=list, help_text='Store array of curvatures')),
                ('paste_detected', models.BooleanField(default=False)),
                ('total_time', models.IntegerField(help_text='Total time to submit in ms')),
                ('classification', models.CharField(help_text="'Human' or 'Bot'", max_length=10)),
                ('human_score', models.FloatField(default=0.0)),
                ('bot_score', models.FloatField(default=0.0)),
                ('human_indicators', models.JSONField(default=list, help_text='Store array of indicators')),
                ('bot_indicators', models.JSONField(default=list, help_text='Store array of indicators')),
                ('bot_fingerprint_score', models.FloatField(default=0.0)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_feature_ratio', models.FloatField(default=0.0)),
                ('mouse_movement_debug', models.JSONField(default=dict, help_text='Store mouse movement debug data')),
                ('speed_calculation_debug', models.JSONField(default=dict, help_text='Store speed calculation debug data')),
                ('post_paste_activity', models.JSONField(default=dict, help_text='Store post paste activity data')),
                ('keyboard_patterns', models.JSONField(default=list, help_text='Store keyboard patterns')),
                ('suspicious_patterns', models.JSONField(default=list, help_text='Store suspicious patterns')),
                ('action_count', models.IntegerField(default=0, help_text='Store total action count')),
                ('is_automated_browser', models.BooleanField(default=False, help_text='Store automated browser flag')),
                ('cursor_entropy', models.FloatField(default=0.0, help_text='Store cursor entropy value')),
                ('scroll_speeds', models.JSONField(default=list, help_text='Store scroll speeds')),
                ('scroll_changes', models.IntegerField(default=0, help_text='Store scroll changes count')),
                ('idle_time', models.BigIntegerField(default=0, help_text='Store idle time in ms')),
                ('honeypot_value', models.CharField(blank=True, help_text='Store honeypot value if any', max_length=255, null=True)),
                ('tabkeycount', models.IntegerField(default=0)),
                ('cursorAngleVariance', models.FloatField(default=0.0, null=True)),
                ('mouseJitter', models.JSONField(default=list)),
                ('micropause', models.JSONField(default=list)),
                ('hesitation', models.JSONField(default=list)),
                ('devicefingerprint', models.CharField(default='0', max_length=255, null=True)),
                ('missing_canvas_fingerprint', models.BooleanField(default=False)),
                ('canvas_metrics', models.JSONField(default=dict)),
                ('unsualscreenresolution', models.JSONField(default=dict)),
                ('gpu_info', models.JSONField(default=dict)),
                ('timing_metrics', models.JSONField(default=dict)),
                ('evasion_signals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'behavioral_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='behavioral__session_e96112_idx'), models.Index(fields=['user_auth'], name='behavioral__user_au_10f958_idx'), models.Index(fields=['classification'], name='behavioral__classif_e22b96_idx'), models.Index(fields=['created_at'], name='behavioral__created_47c3e1_idx'), models.Index(fields=['suspicious_flag'], name='behavioral__suspici_b4e4d5_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignUpAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('usai_id', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'signup_attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['usai_id'], name='signup_atte_usai_id_bca332_idx'), models.Index(fields=['attempt_time'], name='signup_atte_attempt_a66dad_idx'), models.Index(fields=['success'], name='signup_atte_success_0eb884_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserBaselineBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='User identifier (USAI ID or username)', max_length=255)),
                ('session_id', models.CharField(help_text='Session identifier for the baseline collection', max_length=100)),
                ('baseline_user_behavior', models.JSONField(help_text='Complete baseline behavioral data collected during 20-second period')),
                ('collection_start_time', models.DateTimeField(help_text='When baseline collection started')),
                ('collection_end_time', models.DateTimeField(help_text='When baseline collection ended')),
                ('collection_duration_ms', models.IntegerField(help_text='Actual collection duration in milliseconds')),
                ('baseline_metrics', models.JSONField(default=dict, help_text='Calculated baseline metrics (speeds, frequencies, patterns)')),
                ('data_quality_score', models.FloatField(default=0.0, help_text='Quality score of baseline data (0.0 to 1.0)')),
                ('sufficient_interaction', models.BooleanField(default=False, help_text='Whether sufficient user interaction was captured')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this baseline is currently active for comparison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_baseline_behavior',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='user_baseli_user_id_ec554c_idx'), models.Index(fields=['session_id'], name='user_baseli_session_4c1393_idx'), models.Index(fields=['created_at'], name='user_baseli_created_9964f9_idx'), models.Index(fields=['is_active'], name='user_baseli_is_acti_995220_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usai_id', models.CharField(help_text='Unique USAI identifier', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(help_text="User's display name", max_length=255)),
                ('usai_id', models.CharField(help_text='USAI identifier', max_length=100)),
                ('session_type', models.CharField(choices=[('SIGNIN', 'Sign In'), ('SIGNUP', 'Sign Up')], help_text='Type of session - sign in or sign up', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='user_sessio_session_e62ba3_idx'), models.Index(fields=['usai_id'], name='user_sessio_usai_id_ed470b_idx'), models.Index(fields=['created_at'], name='user_sessio_created_c03f8d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SignInAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=100)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('usai_id', models.CharField(max_length=100)),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('attempt_time', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'signin_attempts',
                'ordering': ['-attempt_time'],
                'indexes': [models.Index(fields=['usai_id'], name='signin_atte_usai_id_8afb27_idx'), models.Index(fields=['attempt_time'], name='signin_atte_attempt_428f70_idx'), models.Index(fields=['success'], name='signin_atte_success_384742_idx')],
            },
        ),
    ]
