# Generated by Django 5.2.4 on 2025-08-11 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_userprofile_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupattempt',
            name='email',
        ),
        migrations.RemoveField(
            model_name='signupattempt',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='signupattempt',
            name='user_agent',
        ),
    ]
