# Generated by Django 5.2.4 on 2025-08-11 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_signupattempt_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signupattempt',
            name='ip_address',
        ),
    ]
