# Generated by Django 5.2.4 on 2025-08-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_signupattempt_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user_agent',
        ),
    ]
