# Generated by Django 5.2.4 on 2025-08-11 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_remove_usersession_ip_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BehavioralData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(help_text='Session identifier', max_length=100)),
                ('user_auth', models.CharField(choices=[('Authorized_user', 'Authorized User'), ('Unauthorized_user', 'Unauthorized User')], help_text='User authorization status', max_length=20)),
                ('cursor_movements', models.JSONField(default=list, help_text='Store array of movements')),
                ('key_press_times', models.JSONField(default=list, help_text='Store array of timestamps')),
                ('key_hold_times', models.JSONField(default=list, help_text='Store array of hold durations')),
                ('click_timestamps', models.JSONField(default=list, help_text='Store array of click times')),
                ('click_intervals', models.JSONField(default=list, help_text='Store array of intervals between clicks')),
                ('cursor_speeds', models.JSONField(default=list, help_text='Store array of speeds')),
                ('cursor_acceleration', models.JSONField(default=list, help_text='Store array of accelerations')),
                ('cursor_curvature', models.JSONField(default=list, help_text='Store array of curvatures')),
                ('paste_detected', models.BooleanField(default=False)),
                ('total_time', models.IntegerField(help_text='Total time to submit in ms')),
                ('classification', models.CharField(help_text="'Human' or 'Bot'", max_length=10)),
                ('human_score', models.FloatField(default=0.0)),
                ('bot_score', models.FloatField(default=0.0)),
                ('human_indicators', models.JSONField(default=list, help_text='Store array of indicators')),
                ('bot_indicators', models.JSONField(default=list, help_text='Store array of indicators')),
                ('bot_fingerprint_score', models.FloatField(default=0.0)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_feature_ratio', models.FloatField(default=0.0)),
                ('mouse_movement_debug', models.JSONField(default=dict, help_text='Store mouse movement debug data')),
                ('speed_calculation_debug', models.JSONField(default=dict, help_text='Store speed calculation debug data')),
                ('post_paste_activity', models.JSONField(default=dict, help_text='Store post paste activity data')),
                ('keyboard_patterns', models.JSONField(default=list, help_text='Store keyboard patterns')),
                ('suspicious_patterns', models.JSONField(default=list, help_text='Store suspicious patterns')),
                ('action_count', models.IntegerField(default=0, help_text='Store total action count')),
                ('is_automated_browser', models.BooleanField(default=False, help_text='Store automated browser flag')),
                ('cursor_entropy', models.FloatField(default=0.0, help_text='Store cursor entropy value')),
                ('scroll_speeds', models.JSONField(default=list, help_text='Store scroll speeds')),
                ('scroll_changes', models.IntegerField(default=0, help_text='Store scroll changes count')),
                ('idle_time', models.BigIntegerField(default=0, help_text='Store idle time in ms')),
                ('honeypot_value', models.CharField(blank=True, help_text='Store honeypot value if any', max_length=255, null=True)),
                ('tabkeycount', models.IntegerField(default=0)),
                ('cursorAngleVariance', models.FloatField(default=0.0, null=True)),
                ('mouseJitter', models.JSONField(default=list)),
                ('micropause', models.JSONField(default=list)),
                ('hesitation', models.JSONField(default=list)),
                ('devicefingerprint', models.CharField(default='0', max_length=255, null=True)),
                ('missing_canvas_fingerprint', models.BooleanField(default=False)),
                ('canvas_metrics', models.JSONField(default=dict)),
                ('unsualscreenresolution', models.JSONField(default=dict)),
                ('gpu_info', models.JSONField(default=dict)),
                ('timing_metrics', models.JSONField(default=dict)),
                ('evasion_signals', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'behavioral_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id'], name='behavioral__session_e96112_idx'), models.Index(fields=['user_auth'], name='behavioral__user_au_10f958_idx'), models.Index(fields=['classification'], name='behavioral__classif_e22b96_idx'), models.Index(fields=['created_at'], name='behavioral__created_47c3e1_idx'), models.Index(fields=['suspicious_flag'], name='behavioral__suspici_b4e4d5_idx')],
            },
        ),
    ]
