# Generated by Django 5.2.4 on 2025-08-12 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_behavioraldata'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBaselineBehavior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='User identifier (USAI ID or username)', max_length=255)),
                ('session_id', models.CharField(help_text='Session identifier for the baseline collection', max_length=100)),
                ('baseline_user_behavior', models.JSONField(help_text='Complete baseline behavioral data collected during 20-second period')),
                ('collection_start_time', models.DateTimeField(help_text='When baseline collection started')),
                ('collection_end_time', models.DateTimeField(help_text='When baseline collection ended')),
                ('collection_duration_ms', models.IntegerField(help_text='Actual collection duration in milliseconds')),
                ('baseline_metrics', models.JSONField(default=dict, help_text='Calculated baseline metrics (speeds, frequencies, patterns)')),
                ('data_quality_score', models.FloatField(default=0.0, help_text='Quality score of baseline data (0.0 to 1.0)')),
                ('sufficient_interaction', models.BooleanField(default=False, help_text='Whether sufficient user interaction was captured')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this baseline is currently active for comparison')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_baseline_behavior',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user_id'], name='user_baseli_user_id_ec554c_idx'), models.Index(fields=['session_id'], name='user_baseli_session_4c1393_idx'), models.Index(fields=['created_at'], name='user_baseli_created_9964f9_idx'), models.Index(fields=['is_active'], name='user_baseli_is_acti_995220_idx')],
            },
        ),
    ]
